project/Pokedex/urls.py
from django.urls import path

from Pokedex import views

app_name = 'Pokedex'

urlpatterns = [

    path('', views.home, name="home"),
    path('pokemon_create/', views.pokemon_create, name="pokemon_create"),
    path('pokemon_home/', views.pokemon_home, name="pokemon_home"),
    path('entrenador_create/', views.entrenador_create, name="entrenador_create"),
    path('entrenador_home/', views.entrenador_home, name="entrenador_home"),
    path('entrenador/<int:pk>/edit/', views.entrenador_edit, name='entrenador_edit'),
    path('pokemon/<int:pk>/edit/', views.pokemon_edit, name='pokemon_edit'),
    path('pokemon/<int:pk>/delete/', views.pokemon_delete, name='pokemon_delete'),
    path('entrenador/<int:pk>/delete/', views.entrenador_delete, name='entrenador_delete'),
]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('pokedex/', include('Pokedex.urls', namespace='pokedex')),
    path('login/', views.login_view, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.auth_logout, name='logout'),
    path('home/', views.home, name='home'),
    path('aboutme/', views.aboutme, name="aboutme")
]

project/core/urls.py
from django.urls import path

from . import views

app_name = 'core'

app_name = 'Pokedex'

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.login_view, name="login"),
    path("register/", views.register, name="register"),
    path("logout/", views.auth_logout, name="logout"),
    path("home/", views.home, name="home"),
    path("aboutme/", views.aboutme, name="aboutme"),
]

project/Pokedex/models.py
from django.db import models

class Pokemon(models.Model):
    nombre = models.CharField(max_length=200)
    tipo = models.CharField(max_length=200)
    numero = models.IntegerField(null=True)
    habilidad = models.CharField(max_length=200)
    descripcion = models.TextField()

    def __str__(self):
        return self.nombre
    

class Entrenador(models.Model):
    nombre = models.CharField(max_length=200)
    ciudad_de_origen = models.CharField(max_length=200)
    edad = models.IntegerField()
    historia = models.TextField()

    def __str__(self):
        return self.nombre

project/Pokedex/forms.py
from django import forms

from . import models

class PokemonForm(forms.ModelForm):
    class Meta:
        model = models.Pokemon
        fields = '__all__'

class EntrenadorForm(forms.ModelForm):
    class Meta:
        model = models.Entrenador
        fields = '__all__'

project/Pokedex/views.py
from django.shortcuts import render, redirect, get_object_or_404

from . import models

from .forms import PokemonForm, EntrenadorForm

def home(request):
    query = models.Pokemon.objects.all()
    context = {"pokemons": query}
    return render(request, "Pokedex/index.html", context)

def pokemon_home(request):
    query = models.Pokemon.objects.all()
    context = {"pokemons": query}
    if request.user.is_superuser:
        return render(request, "Pokemon/index_admin.html", context)
    return render(request, "Pokemon/index.html", context)

def pokemon_create(request):
    if request.method == "POST":
        form = PokemonForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("Pokedex:pokemon_home")
        else:
            return render(request, "Pokemon/pokemon_create.html", {"error": form.errors, "form": form})
    else:
        form = PokemonForm()
        return render(request, "Pokemon/pokemon_create.html", {"form": form})

def entrenador_home(request):
    query = models.Entrenador.objects.all()
    context = {"entrenadores": query}
    if request.user.is_superuser:
        return render(request, "Entrenador/index_admin.html", context)
    return render(request, "Entrenador/index.html", context)

def entrenador_create(request):
    if request.method == "POST":
        form = EntrenadorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("Pokedex:entrenador_home")
        else:
            return render(request, "Entrenador/entrenador_create.html", {"error": form.errors, "form": form})
    else:
        form = EntrenadorForm()
    return render(request, "Entrenador/entrenador_create.html", {"form": form})

def entrenador_edit(request, pk):
    entrenador = get_object_or_404(models.Entrenador, pk=pk)
    if request.method == "POST":
        form = EntrenadorForm(request.POST, instance=entrenador)
        if form.is_valid():
            form.save()
            return redirect("Pokedex:entrenador_home")
        else:
            return render(request, "Entrenador/entrenador_create.html", {"form": form, "error": form.errors})
    else:
        form = EntrenadorForm(instance=entrenador)
        print(form)
        return render(request, "Entrenador/entrenador_create.html", {"form": form})
    
def pokemon_edit(request, pk):
    pokemon = get_object_or_404(models.Pokemon, pk=pk)
    if request.method == "POST":
        form = PokemonForm(request.POST, instance=pokemon)
        if form.is_valid():
            form.save()
            return redirect("Pokedex:pokemon_home")
        else:
            return render(request, "Pokemon/pokemon_create.html", {"form": form, "error": form.errors})
    else:
        form = PokemonForm(instance=pokemon)
        return render(request, "Pokemon/pokemon_create.html", {"form": form})
    
def pokemon_delete(request, pk):
    pokemon = get_object_or_404(models.Pokemon, pk=pk)
    if request.method == "POST":
        pokemon.delete()
        return redirect("Pokedex:pokemon_home")
    return render(request, "Pokemon/index.html", {"pokemons": models.Pokemon.objects.all()})

def entrenador_delete(request, pk):
    entrenador = get_object_or_404(models.Entrenador, pk=pk)
    if request.method == "POST":
        entrenador.delete()
        return redirect("Pokedex:entrenador_home")
    return render(request, "Entrenador/index.html", {"entrenadores": models.Entrenador.objects.all()})

project/Pokedex/templates/Pokemon/index.html
{% extends "core/base.html" %}
{% load static %}

{% block title %}
    <h1>¡Registra un nuevo Pokemon!</h1>
{% endblock title %}

{% block content %}
{% if user.is_superuser %}
<div class="d-flex ms-3"><a class="btn btn-primary" href="{% url 'Pokedex:pokemon_create' %}">Agregar Pokemon</a></div>
{% endif %}
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <div class="d-flex float-end">
        <a class="btn btn-primary" href="/"> <<  Back</a>
      </div>
    </div>
  </div>
  <div class="row">
    {% for pokemon in pokemons %}
    <div class="col-2 d-flex align-items-stretch">
        <div class="card mt-3" style="width: 18rem;">
            <div class="d-flex justify-content-center mt-2">
              <img src="{% static '/pokemon/' %}{{pokemon.numero}}.png" class="rounded-circle " width="200" height="200">
            </div>

            <div class="card-body d-flex flex-column">
              <h5 class="card-title text-center">{{ pokemon.numero }}</h5>
              <h3 class="text-center">{{ pokemon.nombre }}</h3>
              <ul class="list-group list-group-flush flex-grow-1">
                <li class="list-group-item">Tipo: {{ pokemon.tipo }}</li>
                <li class="list-group-item">Habilidad: {{ pokemon.habilidad }}</li>
                <li class="list-group-item">{{ pokemon.descripcion }}</li>
              </ul>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
</div>



{% endblock content %}

project/Pokedex/templates/Pokemon/index_admin.html
{% extends "core/base.html" %}
{% load static %}

{% block title %}
<h1>¡Registra un Entrenador!</h1>
{% endblock title %}

{% block content %}
{% if user.is_superuser %}
<div class="d-flex ms-3"><a class="btn btn-primary" href="{% url 'Pokedex:pokemon_create' %}">Agregar Pokemon</a></div>
{% endif %}
<div class="container-fluid">
    <div class="row">
        <table class="table table-borderless table-hover">
            <thead>
                <tr>
                    <th>Número</th>
                    <th>Pokémon</th>
                    <th>Tipo</th>
                    <th>Habilidad</th>
                    <th>Descripción</th>
                    <th>Imagen</th>
                    <th>Acción</th>
                </tr>
            </thead>
            <tbody>
                {% for pokemon in pokemons %}
                <tr>
                    <td colspan="1">{{ pokemon.numero }}</td>
                    <td>{{ pokemon.nombre }}</td>
                    <td>{{ pokemon.tipo }}</td>
                    <td>{{ pokemon.habilidad }}</td>
                    <td colspan="1">{{ pokemon.descripcion }}</td>
                    <td><img src="{% static '/pokemon/' %}{{pokemon.numero}}.png" class="rounded-circle" width="75" height="75"></td>
                    <td colspan="3">
                        <a class="btn btn-warning mb-1 me-2" href="{% url 'Pokedex:pokemon_edit' pokemon.pk %}">Editar</a>
                        <button class="btn btn-danger" data-toggle="modal" data-target="#deleteModal" data-id="{{ pokemon.pk }}">Eliminar</button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">¿Confirma Eliminar?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ¿Estás seguro que deseas eliminar este Pokémon?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <form method="post" id="deleteForm" action="">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Eliminar</button>
                </form>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script>
    $('#deleteModal').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget);
        var pokemonId = button.data('id');
        var action = "{% url 'Pokedex:pokemon_delete' 0 %}".replace('0', pokemonId);
        var modal = $(this);
        modal.find('#deleteForm').attr('action', action);
    });
</script>
{% endblock content %}

project/Pokedex/templates/Pokemon/pokemon_create.html
{% extends "core/base.html" %}

<style>
    ul {color:red;}
    li {color:blue;} 
</style>

{% block content %}

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-4">
            <form method="post"> 
                {% csrf_token %}
                <div class="form-group">
                    {% for field in form %}
                        <div class="mb-3">
                            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                            {% if field.errors %}
                                {{ field.errors }}
                            {% endif %}
                            {% if field.name == 'descripcion' %}
                                <textarea class="form-control" id="{{ field.id_for_label }}" name="{{ field.html_name }}">{{ field.value|default_if_none:'' }}</textarea>
                            {% else %}
                                <input type="{{ field.field.widget.input_type }}" class="form-control" id="{{ field.id_for_label }}" name="{{ field.html_name }}" value="{{ field.value|default_if_none:'' }}">
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
                <button type="submit" class="btn btn-primary">Guardar</button>
            </form
        </div>
    </div>
</div>
{% endblock content %}