project/Pokedex/urls.py
from django.urls import path

from Pokedex import views

app_name = 'Pokedex'

urlpatterns = [

    path('', views.home, name="home"),
    path('pokemon_create/', views.pokemon_create, name="pokemon_create"),
    path('pokemon_home/', views.pokemon_home, name="pokemon_home"),
    path('entrenador_create/', views.entrenador_create, name="entrenador_create"),
    path('entrenador_home/', views.entrenador_home, name="entrenador_home"),
    path('entrenador/<int:pk>/edit/', views.entrenador_edit, name='entrenador_edit'),
    path('pokemon/<int:pk>/edit/', views.pokemon_edit, name='pokemon_edit'),
    path('pokemon/<int:pk>/delete/', views.pokemon_delete, name='pokemon_delete'),
    path('entrenador/<int:pk>/delete/', views.entrenador_delete, name='entrenador_delete'),
]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('pokedex/', include('Pokedex.urls', namespace='pokedex')),
    path('login/', views.login_view, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.auth_logout, name='logout'),
    path('home/', views.home, name='home'),
    path('aboutme/', views.aboutme, name="aboutme")
]

project/core/urls.py
from django.urls import path

from . import views

app_name = 'core'

app_name = 'Pokedex'

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.login_view, name="login"),
    path("register/", views.register, name="register"),
    path("logout/", views.auth_logout, name="logout"),
    path("home/", views.home, name="home"),
    path("aboutme/", views.aboutme, name="aboutme"),
]

project/core/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.core.exceptions import ValidationError


class CustomUserManager(BaseUserManager):
    def create_user(self, username, password=None, **extra_fields):
        if not username:
            raise ValueError('The Username field must be set')
        if not password or len(password) < 4:
            raise ValidationError('La contraseña debe tener al menos 4 caracteres')
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(username, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=200, unique=True)
    profile_pic = models.ImageField(upload_to='profile_pics/', null=True, blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(null=True, blank=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []

    def str(self):
        return self.username

project/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model

from . import views

from . import models
User = get_user_model()
class CustomUserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirmar Contraseña', widget=forms.PasswordInput)
    profile_pic = forms.CharField(label='Profile Pic', max_length=1000, required=False)
    class Meta:
        model = User
        fields = ['username', 'profile_pic']

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Las contraseñas no coinciden")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(max_length=254, widget=forms.TextInput(attrs={'autofocus': True}))
    password = forms.CharField(label="Password", strip=False, widget=forms.PasswordInput)

project/core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, logout
from django.contrib.auth import login as auth_login
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import CustomUserCreationForm, CustomAuthenticationForm


def home(request):
    return render(request, 'core/index.html')


def login_view(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return render(request, 'core/index.html')
            else:
                messages.error(request, 'Nombre de usuario o contraseña incorrectos.')
        else:
            messages.error(request, 'Formulario inválido.')
    else:
        form = CustomAuthenticationForm()
    return render(request, 'core/login.html', {'form': form})

def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            auth_login(request, user)
            return redirect('Pokedex:pokemon_home')
        else:
            form2 = CustomUserCreationForm()
            return render(request, 'core/register.html', {'form': form2,'error':form.errors})
    else:
        form = CustomUserCreationForm()
        return render(request, 'core/register.html', {'form': form})


def auth_logout(request):
    logout(request)
    form = CustomAuthenticationForm
    return render(request, 'core/login.html', {'form': form})


def aboutme(request):
    return render(request, 'core/aboutme.html')

project/core/templates/core/aboutme.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}
    SOBRE MI
{% endblock title %}

{% block content %}
<div class="container">
<div class="row">
    <div class="col-12">
      <div class="d-flex float-end">
        <a class="btn btn-primary" href="/"> <<  Back</a>
      </div>
    </div>
  </div>
    <div class="row text-center">
        <div class="col-lg-12 d-flex align-items-center" style="margin-top: 50px";>
            <img class="rounded" src="{% static 'shorsh.png' %}" alt="Imagen" style="max-width: 300px; height: 300px; margin-left: 30px;">
            <div style="text-align: justify; margin-left: 30px;">
                <p>¡Hola! Mi nombre es Jorge, pero todos los que me conocen me dicen Shorsh. ¡Siéntanse libres!</p>
                <p>Tengo 35 años y entre mis aficiones y pasiones se encuentran mi familia, amigos, los videojuegos, el básquet, Pokémon, etc.
                    Asimismo, soy un orgulloso gym rat que no falta un día a entrenar. Tengo una gata tricolor que se llama Suri y es quien me
                    hace compañía en mi día a día.
                    Mi lóngevo fanatismo por Pokémon y todas sus formas de contenido son lo que me llevó a crear este sitio como temática para 
                    mi proyecto final. ¡Espero que haya entre quienes le echen una mirada a este pequeño proyecto gente tan pokefanática como yo!
                    Disfruten mucho y, por sobre todas las cosas, ¡atrápenlos a todos!
        </div>
    </div>
</div>
{% endblock content %}

project/core/templates/core/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pokédex: Tu enciclopedia Pokémon online</title>
    <link rel="icon"
              type="image/x-icon"
              href="{% static 'core/assets/favicon.ico' %}"/>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f5f5f5;
        }

        .logo {
            text-align: center;
            margin-top: 50px;
        }

        .logo h1 {
            font-family: 'Arial Black', sans-serif;
            font-size: 26px;
            color: #0c0c0c;
            letter-spacing: 2px;
            text-shadow: 2px 2px 4px #000000;
            -webkit-text-stroke: 0.8px white;
        }
        
        table {
            border-bottom: none !important;
        }

        .text {
            font-family: Verdana, Geneva, Tahoma, sans-serif;
        }

        .navcolor {
            background-color: #1d0fa7;
        }

        .text-yellow {
            color: #eee043 !important; 
        }

        .bg-footer {
            background-color: rgba(128, 128, 128, 0.555);
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light navcolor sticky-top">
        <div class="container">
            <a class="navbar-brand text-yellow" href="{% url 'home' %}">Home</a>
            <a class="navbar-brand text-yellow" href="{% url 'Pokedex:entrenador_home' %}">Entrenadores</a>
            <a class="navbar-brand text-yellow" href="{% url 'Pokedex:pokemon_home' %}">Pokémon</a>
            <a class="navbar-brand text-yellow" href="{% url 'aboutme' %}">About Me</a>
            {% if not user.is_authenticated %}
            <a class="navbar-brand text-yellow" href="{% url 'login' %}">Login</a>
            <a class="navbar-brand text-yellow" href="{% url 'register' %}">Registrarse</a>
            {% endif %}
            {% if user.is_authenticated %}
            <div class="d-flex align-items-center">
            {%if user.profile_pic and user.profile_pic != ''%}
                <img class="rounded-circle ml-5"src="{{ user.profile_pic }}" alt="Profile Picture" width="50" height="50">
            {%else%}
                <div class="rounded-circle bg-success me-2" style="width: 25px;height: 25px;"></div>
            {%endif%}
                <span class="text-yellow text-bold ">{{user.username}}</span>
            </div>

            <a class="navbar-brand text-yellow" href="{% url 'logout' %}">Logout</a>
            {% endif %}
        </div>
    </nav>
    <div class="logo">
        <img src="{% static 'Pokedex.png' %}" alt="">
        <div class="text-center fs-3" style="margin-top: -65px; margin-right: 70px;"><h1>Tu enciclopedia Pokémon online</h1></div>
    </div>
    {% block content %}

    {% endblock content %}

    {% bootstrap_javascript %}

    <footer class="py-2 bg-footer fixed-bottom">
        <div class="float-start px-4 px-lg-5">
            <p class="m-0 text-center text-white">©Pokédex, todos los derechos reservados.</p>
        </div>
    </footer>
</body>
</html>

project/core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}
        <h1>¡Bienvenido a Pokédex!</h1>
{% endblock title %}

{% block content %}
        <div class="text-center me-4 mt-3 "><h1>¡Bienvenido!</h1></div>
<div class="logo">
        <img src="{% static '151pokemon.png' %}" alt="" height="550" width="1500">
        <div class="text-center fs-3" style="margin-top: -35px; margin-right: -25px;"><h1>Créditos de la imagen: scholan.club</h1></div>
    </div>
{% endblock content %}

project/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-12 col-xl-3">
      <h1 class="text-center">Iniciar Sesión</h1>
      {% if error %}
      <p style="color: blue; font-weight: bold" class="text-center">ERROR: {{ error }}</p>
      {% endif %}
      <form method="post" action="{% url 'login' %}">
          {% csrf_token %}
          <div class="form-group">
            <label for="usermane">Username:</label>
            <input type="text" class="form-control" name="username" value="{{ field.value|default_if_none:'' }}">
          </div>
          <div class="form-group">
            <label for="usermane">Password:</label>
            <input type="password" class="form-control" name="password" value="{{ field.value|default_if_none:'' }}">
          </div>
          <div class="text-center mt-3">
            <button type="submit" class="btn btn-primary btn-block">Log in</button>
          </div>

      </form>
    </div>
  </div>
</div>
{% endblock content %}

project/core/templates/core/register.html
{% extends 'core/base.html' %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1 class="text-center">Regístrate</h1>
      {% if error %}
      <p style="color: blue; font-weight: bold" class="text-center">ERROR: {{ error }}</p>
      {% endif %}
      <form method="post" action="{% url 'register' %}"> 
          {% csrf_token %}
          <div class="form-group">
            <label for="usermane">Username:</label>
            <input type="text" class="form-control" name="username" >
          </div>
          <div class="form-group">
            <label for="profile_pic">Profile Picture:</label>
            <input type="text" class="form-control" name="profile_pic" >
          </div>
          <div class="form-group">
            <label for="password1">Password:</label>
            <input type="password" class="form-control" name="password1">
          </div>
          <div class="form-group">
            <label for="password2">Confirm Password:</label>
            <input type="password" class="form-control" name="password2" >
          </div>
          <div class="text-center mt-2">
            <button type="submit" class="btn btn-primary btn-block mt-2">Guardar</button>
          </div>

      </form>
    </div>
  </div>
</div>
{% endblock content %}